dangdang02/dangdang/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('register/', include('register.urls')),
    path('login/', include('login.urls')),
]

dangdang02/home/urls.py
from django.contrib import admin
from django.urls import path

import home
from home import views

app_name='home'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index,name='index'),
    path('book_detial/', views.book_detial,name='book_detial'),
    path('book_list/', views.book_list,name='book_list'),
    path('uquit/', views.uquit,name='uquit'),
    path('shopcar/', views.shopcar,name='shopcar'),
    path('addbook/', views.addbook,name='addbook'),
    path('update/', views.update,name='update'),
    path('delbook/', views.delbook,name='delbook'),
    path('indent/', views.indent,name='indent'),
    path('showindent/', views.showindent,name='showindent'),
    path('ajaxshow/', views.ajaxshow,name='ajaxshow'),
    path('ddtj/', views.ddtj,name='ddtj'),
    path('ddtiaj/', views.ddtiaj,name='ddtiaj'),
]

dangdang02/login/urls.py
from django.contrib import admin
from django.urls import path, include

from login import views

app_name='login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('login_logic/', views.login_logic, name='login_logic'),
    path('getcapt/', views.getcapt, name='getcapt')
]

dangdang02/register/urls.py
from django.contrib import admin
from django.urls import path, include

from register import views

app_name='register'
urlpatterns = [
    path('registe/',views.registe,name='registe'),
    path('capt/',views.capt,name='capt'),
    path('check/',views.checkname,name='checkname'),
    path('captcheck/',views.captcheck,name='captcheck'),
    path('regidterok/',views.regidterok,name='regidterok'),
    path('regokjump/',views.regokjump,name='regokjump'),
    path('email/',views.email,name='email'),
]

dangdang02/login/models.py
from django.db import models

# Create your models here.

dangdang02/register/models.py
from django.db import models

# Create your models here.

dangdang02/login/views.py
import random
import string
import hashlib
from django.shortcuts import render,HttpResponse,redirect
from django.urls import reverse

from home.models import *
from yanzhengma.image import ImageCaptcha



def login(request):
    name_cook=request.COOKIES.get('name')
    if name_cook:
        if TUser.objects.filter(username=name_cook):
            ur=reverse('home:index')
        return redirect(ur+'?name='+name_cook)
    return render(request,'login.html')

def login_logic(request):
    name=request.POST.get('name')
    pwd=request.POST.get('pwd')
    capt=request.POST.get('capt')
    cook=request.POST.get('cook')
    captr=request.session.get('logcapt')
    url=request.session.get('url')

    if capt.upper()==captr.upper():
        # req = HttpResponse(reverse('home:index'))
        salt=TUser.objects.filter(username=name)
        if salt:
            salt = TUser.objects.filter(username=name)[0].salt
            pwdadd = pwd + salt
            sha = hashlib.md5()
            sha.update(pwdadd.encode())
            pwdaddmi = sha.hexdigest()
            if TUser.objects.filter(username=name, password=pwdaddmi, salt=salt):
                if TUser.objects.filter(username=name, password=pwdaddmi, salt=salt)[0].is_active:
                    if '?' in url:
                        req = HttpResponse(url + '&name=' + name)
                    else:
                        req = HttpResponse(url + '?name=' + name)
                    if cook:
                        name = req.set_cookie('name', name, max_age=7 * 24 * 3600)
                    return req
                else:
                    return HttpResponse('1')
        else:
            return HttpResponse('0')
    return HttpResponse('0')


def getcapt(request):
    str1=''.join(random.sample(string.ascii_letters+string.digits,4))
    capt=ImageCaptcha().generate(str1)
    request.session['logcapt']=str1
    return HttpResponse(capt,'image/png')

dangdang02/register/views.py
import random,string
import hashlib,uuid
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from django.contrib.auth import settings
from django.core.mail import send_mail
from django.shortcuts import render,HttpResponse,redirect

# Create your views here.
from yanzhengma.image import ImageCaptcha
from home.models import  *


def registe(request):
    return render(request,'register.html')

def capt(request):
    str1=''.join(random.sample(string.ascii_letters+string.digits,4))
    img=ImageCaptcha().generate(str1)
    request.session['rcapt']=str1
    return HttpResponse(img,'image/png')

def checkname(request):
    name=request.POST.get('name')
    if TUser.objects.filter(username=name):
        return  HttpResponse(0)
    return HttpResponse(1)

def regidterok(request):
    salt=str(uuid.uuid4())
    name=request.POST.get('txt_username')
    pwd=request.POST.get('txt_password')+salt
    sha=hashlib.md5()
    sha.update(pwd.encode())
    pwd_addmi=sha.hexdigest()
    TUser.objects.create(username=name,password=pwd_addmi,salt=salt)
    userid=TUser.objects.filter(username=name)[0].id
    ser=Serializer(settings.SECRET_KEY,expires_in=120)
    token=ser.dumps({'id':userid})
    token=token.decode('utf-8')
    send_mail('激活用户', 'http://127.0.0.1:8000/register/email/?token='+token, '799225778@qq.com', [name], fail_silently=False)
    return render(request,'register ok.html',{'name':name})

def captcheck(request):
    captr=request.session.get('rcapt')
    capt=request.GET.get('code')
    if capt.upper()==captr.upper():
        return HttpResponse('1')
    return HttpResponse('0')


def regokjump(request):
    name=request.GET.get('name')
    url=request.session.get('url')
    if '?' in url:
        url=request.session.get('url')+'&name='+name
    else:url=request.session.get('url')+'?name='+name
    return redirect(url)


def email(request):
    token=request.GET.get('token')
    ser=Serializer(settings.SECRET_KEY,expires_in=120)
    result=ser.loads(token)
    id=result.get('id')
    tuser=TUser.objects.filter(id=id)[0]
    tuser.is_active=True
    tuser.save()
    return HttpResponse('激活成功')

dangdang02/templates/indent ok.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
<script src="/static/js/jquery_1.8.js"></script>
    <script src="/static/js/jquery_cookie.js"></script>
	<link rel="shortcut icon" href="/static/images/favicon.ico?v=20160901" type="image/x-icon">
    <link href="/static/css/shopping_cart_new.css" rel="stylesheet" type="text/css">
	<link href="/static/css/footer_150526.css" rel="stylesheet" type="text/css" />
</head>

<body style="padding-bottom:82px">

<link href="/static/css/header_960_150611.css" rel="stylesheet" type="text/css">
<script src="/static/js/pagetop2015_0827.js" charset="gb2312" type="text/javascript"></script>

<div id="hd">
<div id="tools">
<div class="tools">
    <div class="ddnewhead_operate" dd_name="顶链接">
        
        <div class="ddnewhead_welcome" display="none;">
            <span id="nickname"><span class="hi">Hi，<a href="http://myhome.dangdang.com/" class="login_link" target="_blank"><b>159**…</b></a><a href="javascript:PageTopSignOut();" target="_self">[退出]</a></span></span>
            <div class="tel_pop" style="display:none" id="__ddnav_sjdd" onmouseover="showgaoji('a_phonechannel','__ddnav_sjdd');" onmouseout="hideotherchannel('a_phonechannel','__ddnav_sjdd');">
                <a target="_blank" href="http://t.dangdang.com/20130220_ydmr" class="title"><i class="icon_tel"></i>手机当当</a><i class="title_shadow"></i>
                <ul class="tel_pop_box">
                    <li><a href="http://t.dangdang.com/20130220_ydmr" dd_name="手机二维码"><span>当当手机客户端</span><img src="http://img3.ddimg.cn/00363/doc/erweima2.png"><span class="text">随手查订单<br>随时享优惠</span></a></li>
                </ul>
            </div>
        </div>
        <div class="new_head_znx" id="znx_content" style="display:none;"></div>
    </div>
</div>
</div>
<div id="header_end"></div>
</div>
<form action="http://search.dangdang.com/search.aspx" id="bootpagetopSearch" name="bootpagetopSearch" method="GET"></form>
<script type="text/javascript">var nick_num = 0;initHeaderOperate();</script><script type="text/javascript" src="http://orderb.dangdang.com/queryunpaid?callback=Unpaid_Data"></script>
		<div class="shoppingcart_wrapper" id="ad_cpt_11850"><div><a href="http://a.dangdang.com/tjump.php?q=ddo84XQOf357bOs8tXGg5%2F%2F0oVoDImt3DFWsMqu7ZMSVsfUMeOQJueASNiMLjq%2FdrXMLCKnVfyKEahteAh1ih%2ByKYrKGzhvL20LVbDzObRambBA0YPpivy5hR5foQ4Rt%2BTB" target="_blank" rel="nofollow"><img src="http://img62.ddimg.cn/2017/1/11/2017011111344969879.jpg"></a></div></div>
<div class="logo_line">
    <div class="w960">
        <div class="shopping_procedure02 shopping_procedure "><span>我的购物车</span><span>填写订单</span><span class="current">完成订单</span></div>
        <div class="logo"><a href="#"><img src="/static/images/bz_logo_car.jpg" alt=""></a></div>
    </div>
</div>
<div class="checkout-wrap"><div class="indent_con">
	<div class="order-box orderEnd-box">
            <div class="orderEnd-box-top">
                <div class="topbar">
                </div>
                <h2>
                    <span id="spanOrderTip" class="text">感谢您提交订单，我们将及时为您处理！</span>
                    
                   
                </h2>
               
            </div>
            <div class="orderEnd-box-cont">
                <div id="NotPeerPayOrderList" class="pay-instead-order"> 
                
                
                </div>
                <div class="pay-normal" id="order_list"> <div class="item-order"><h3>订单：<a href="http://order.dangdang.com/orderdetails.aspx?orderid=34673930343" target="_blank"><span class="number">{{ ordernum }}</span></a></h3><div class="cont minh-40"><table cellpadding="0" cellspacing="0">	 		<tbody><tr><td width="53"></td><td>		<span class="popup-Details spd">1件商品<i class="icon icon-details"></i><div class="popup-wrap popup-orderEnd-detail" style="right:-288px; top:12px;display:none;"><div class="popup-cont">		 			<p><span class="span-w230">活着（余华经典著作）</span><strong class="color-orange">x1</strong></p>				</div></div></span>			    	        <div class="popup-wrap popup-orderEnd-detail" style="right:-288px; top:12px;display:none;"><div class="popup-cont">			 				<p><span class="span-w230">活着（余华经典著作）</span><strong class="color-orange">x1</strong></p></div></div><span>送给</span><span class="popup-Details spd">{{ name }}<i class="icon icon-details"></i><div class="popup-wrap popup-orderEnd-detail" style="right:-288px; top:12px;display:none;"><div class="popup-cont"><p>中国 北京 北京市 海淀区 西二旗铭科苑小区十一号楼二单元601 100019</p><p>电话：15901551248</p></div></div></span><span>配送方为</span><span>当当网</span>   		</td></tr>							<tr class="hackie6"><td>&nbsp;</td></tr>					</tbody></table></div>					<div class="order-price"><p>支付金额：<span class="price-d">¥{{ money }}</span>        </p><p class="p-hdfk">货到付款</p></div>					<div class="itemtext"><span class="color-red">安全提醒：</span>当当平台及销售商不会以订单异常、系统升级等理由，通过任何方式发送给您退款链接。请您谨防<span class="color-red">钓鱼链接或诈骗电话</span>！</div></div></div>
                
                <div class="item-order item-order-payment" id="error_prompt" style="display:none;"> <!-- 需要隐藏，添加hide类即可 -->
                    <div class="tips-pay">
                        <strong>温馨提示：</strong>
                        <span>如果您有网上支付、银行转账的订单，请您在<strong class="color-red">24</strong>小时内支付 <a href="http://order.dangdang.com/myallorders" id="a_myorder">查看订单</a> </span><br>
                        <span style="padding-left:67px;">您还有 <strong class="color-red">1</strong> 张"待提交"订单 <a href="http://shopping.dangdang.com/shoppingcart/dispart_order.aspx" id="a_submitorder">继续提交</a></span>
                    </div>
                </div>
            </div>
        </div>
    
     
</div></div>

<div id="footer">
<div class="footer">
	<div class="footer_nav_box">
		<div class="footer_copyright"><span>Copyright (C) 当当网 2004-2014, All Rights Reserved</span><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img" rel="nofollow"><img src="http://img4.dangdang.com/bottom/validate.gif"></a><span><a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow">京ICP证041189号</a></span><span>出版物经营许可证&nbsp;新出发京批字第直0673号</span></div>
	</div>
</div>
</div>
    <div class="foot_tip_ad">广告</div>
    <style>
        .foot_tip_ad { width:40px; height:40px; font:12px/40px "simsun"; text-align:center; color:#fff; background-color:#474747; position:fixed; right:0; bottom:10px;_position:absolute; _bottom:auto;_top:expression(eval(document.documentElement.scrollTop+document.documentElement.clientHeight-this.offsetHeight-(parseInt(this.currentStyle.marginTop,10)||0)-(parseInt(this.currentStyle.marginBottom,10)||0)));}
    </style>


</body>
</html>

dangdang02/templates/register ok.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>无标题文档</title>
<link type="text/css" href="/static/css/register_150706.css" rel="stylesheet">
<link href="/static/css/unite_header_1129.css" rel="stylesheet" type="text/css">
<script src="/static/js/zhuce/pagetop_20121010.js"type="text/javascript"></script>
</head>

<body>
<div class="ddnewhead_wrap">
    <div class="ddnewhead_content ddnewhead_content2">
        <div class="ddnewhead_operate" id="__ddnav_menu">
          
          <p id="nickname">欢迎光临当当网，请<a name="ddnav_login" href="https://login.dangdang.com/signin.aspx?returnurl=https%3A//login.dangdang.com/register.php%3Freturnurl%3Dhttp%3A//book.dangdang.com/" target="_self" class="login_link">登录</a><a name="ddnav_register" href="https://login.dangdang.com/Register.aspx" target="_self" class="login_link">免费注册</a></p>
    </div>
              <div class="ddnewhead_logo"><a href="http://www.dangdang.com" title="返回首页" name="ddnav_logo"><img src="/static/images/zc_logo.jpg" alt="百知网"></a></div>
      <div class="clear"></div>
    </div>
     <div class="ddnewcarthead_bottom"></div>
</div>
<form id="register_form" method="post" action="register.php" onsubmit="return false;">
        	<input style="display: none;" type="password">
            <div id="bd">
				<!--默认-->
				<div class="shadow_box">
					<div class="register_box">
						<div class="head">
							<span class="dd_more"><a href="http://www.dangdang.com" class="home">当当首页</a><a href="http://help.dangdang.com/details/page2">注册帮助</a></span>
							<a href="javascript:void(0);" class="head_a head_a1">新用户注册</a>
							<!--<a href="register_company.php?returnurl=http://book.dangdang.com/" class="head_a">企业用户注册</a>-->
						</div>
						<div class="body zccg">
							<p>恭喜您，注册成功！</p>
                            <ul><li class="first">手机号码</li><li class="last">{{ name }}</li></ul>
                            <div class="zccg_btn"><a href="{% url 'register:regokjump' %}?name={{ name }}">立即购物</a><span><em>6</em>秒后自动返回……</span></div>
						</div>
					</div>
				</div>
			</div>
            <input id="btn_confirm" style="display: none" type="submit">
			<input name="hdn_username" id="hdn_username" type="hidden">
			<input name="hdn_mobile" id="hdn_mobile" type="hidden">
			<input name="hdn_password" id="hdn_password" type="hidden">
			<input name="action_post" id="action_post" value="register" type="hidden">
			<input name="returnurl" id="returnurl" value="http://book.dangdang.com/" type="hidden">
        </form>
        <style type="text/css">
    .footer_nav_box{border-top: 1px solid #ebebeb;width:100%;_width:expression(this.scrollWidth < 960 ? "960px" : "auto");min-width: 960px;padding: 17px 0 50px;}
    .footer_nav_box a,.footer_nav_box{color: #8c8c8c;font-size: 12px;text-decoration: none;}
    .footer_nav_box a:hover{color: #f48570;text-decoration: underline;}
    .footer_nav_box .footer_nav{text-align: center;line-height: 20px;padding-bottom: 17px;padding-top: 25px;}
    .footer_nav_box .footer_nav span.sep{margin: 0 17px 0 19px;}
    .footer_nav_box .footer_copyright{line-height: 20px;text-align: center;width: 960px;margin: 0 auto;}
    .footer_nav_box .footer_copyright span.sep{margin:0 17px 0 19px;}
    .footer_nav_box .footer_icon{padding: 10px 0 0 340px;width: 640px;margin: 0 auto;height: 77px;}
    .footer_nav_box .validator,.footer_nav_box .knet{float:left;display:inline;padding:15px 5px 15px;width:135px;height:47px;}

    .footer_copyright {padding: 10px 0 0 0; margin: 0 auto;float: none; width: auto;text-align: center;color: #8c8c8c;}
    .footer_copyright span, .public_footer .footer_copyright a.footer_img { display: inline-block; float: none; }
    .footer_copyright a { padding: 0 4px; color: #8c8c8c;font-size: 12px;text-decoration: none;}
    .footer_copyright a:hover{color: #f48570;text-decoration: underline;}
    .footer_nav_box .footer_nav .footer_hot_search{display:inline-block;*display:inline;width:50px;position:relative}
    .footer_nav_box .footer_nav .pos_a_box{position:absolute;left:-251px;top:22px;background-color:#f48570;width:300px;border-radius:8px;text-align:center;height:14px;line-height:14px}
    .footer_nav_box .footer_nav .pos_a_box a,.footer_nav_box .footer_nav .pos_a_box a:hover,.footer_nav_box .footer_nav .pos_a_box span{padding:0 2px;color:#fff;text-decoration:none}
    .footer_nav_box .footer_nav .pos_a_box i{display:block;width:0;height:0;line-height:0;font-size:0;border-width:0 4px 4px;border-style:solid;border-color:#fff #fff #f48570 #fff;position:absolute;right:20px;top:-4px}
</style>
<div class="footer_nav_box">
    <div class="footer_nav"><a href="http://static.dangdang.com/topic/2227/176801.shtml" target="_blank" rel="nofollow">公司简介</a><span class="sep">|</span><a href="http://ir.dangdang.com/" target="_blank">Investor Relations</a><span class="sep">|</span><a href="http://zhaopin.dangdang.com" target="_blank">诚聘英才</a><span class="sep">|</span><a href="http://static.dangdang.com/topic/744/200778.shtml" target="_blank">手机当当</a><span class="sep">|</span><a href="http://union.dangdang.com/" target="_blank">网站联盟</a><span class="sep">|</span><a href="http://outlets.dangdang.com/merchants_open" target="_blank">当当招商</a><span class="sep">|</span><a href="http://misc.dangdang.com/groupbuy/Default.aspx" target="_blank" rel="nofollow">机构销售</a><span class="sep">|</span><a href="http://blog.dangdang.com/" target="_blank">官方Blog</a>
        <script>
            var setTo = null;
            function showghotsearch() {
                clearTimeout(setTo);
                document.getElementById("hot_search_content").style.display = "block";
            }
            function hidehotsearch() {
                setTo = setTimeout(function() {
                    document.getElementById("hot_search_content").style.display = "none";
                }, 100)
            }
        </script>   		
    </div>
    <div class="footer_copyright"><span>Copyright (C) 当当网 2004-2017, All Rights Reserved</span></div>
    <div class="footer_copyright"><span><a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow">京ICP证041189号</a></span><span class="sep">|</span><span>出版物经营许可证 新出发京批字第直0673号</span><span class="sep">|</span><span>食品流通许可证：SP1101011010021855(1-1)</span><br><span>互联网药品信息服务资格证编号：(京)-非经营性-2012-0016</span><span class="sep">|</span><span>京公网安备110101000001号</span></div>
    <!-- 有三个icon的时候加footer_icon2 -->
    <div class="footer_icon footer_icon2" style="padding-left: 55px;">
        <div class="validator"><a href="http://www.hd315.gov.cn/beian/view.asp?bianhao=010202001051000098" target="_blank" class="footer_img"><img src="images/validate.gif"></a></div>
        <div class="knet"><!-- 可信网站LOGO安装开始 -->
            <script type="text/JavaScript">
                function CNNIC_change(eleId) {
                var str = document.getElementById(eleId).href;
                var str1 = str.substring(0, (str.length - 6));
                str1 += CNNIC_RndNum(6);
                document.getElementById(eleId).href = str1;
                }

                function CNNIC_RndNum(k) {
                var rnd = "";
                for (var i = 0; i < k; i++)
                rnd += Math.floor(Math.random() * 10);
                return rnd;
                }
            </script>
            <a href="https://ss.knet.cn/verifyseal.dll?sn=2010091900100002234&amp;pa=2940051" tabindex="-1" id="urlknet" target="_blank" rel="nofollow"><img alt="可信网站" name="CNNIC_seal" src="/static/images/knetSealLogo.png" oncontextmenu="return false;" onclick="CNNIC_change('urlknet')" width="128" height="47" border="true"></a><!-- 可信网站LOGO安装结束 -->
        </div>
        <div class="validator"><a href="http://bj429.com.cn/" target="_blank" class="footer_img"><img src="/static/images/7d593c48-48f6-4fc9-85e0-7d6e10dfc2a2.hpvgUvc9"></a></div>
        <div class="validator"><a id="_pingansec_bottomimagesmall_brand" href="http://si.trustutn.org/info?sn=302161014024825726885&amp;certType=1" target="_blank"><img src="/static/images/brand_128_47.png"></a></div>
        <div class="clear"></div>
    </div>
</div>
</body>
</html>